namespace DemoDWS
{
    partial class Form1DWS
    {
       ///<summary>
        ///Required designer variables.
        ///</summary>
        private System.ComponentModel.IContainer components = null;

///<summary>
        ///Clean up all resources in use.
        ///</summary>
        ///<param name="dispose"> true if managed resources should be released; otherwise, false. </param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Code generated by the form designer

        /// <summary>
        ///Designer supports required methods -do not modify
        ///Use the code editor to modify the contents of this method.
        /// </summary>
        private void InitializeComponent()
        {
			this.components = new System.ComponentModel.Container();
			this.lblCodeCount = new System.Windows.Forms.Label();
			this.btnClose = new System.Windows.Forms.Button();
			this.lblCode = new System.Windows.Forms.Label();
			this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
			this.gbBasic = new System.Windows.Forms.GroupBox();
			this.button1 = new System.Windows.Forms.Button();
			this.btnStart = new System.Windows.Forms.Button();
			this.groupBox5 = new System.Windows.Forms.GroupBox();
			this.listBoxLog = new System.Windows.Forms.ListBox();
			this.groupBox4 = new System.Windows.Forms.GroupBox();
			this.Pan_Dis = new System.Windows.Forms.Panel();
			this.panel1 = new System.Windows.Forms.Panel();
			this.gbBasic.SuspendLayout();
			this.groupBox5.SuspendLayout();
			this.groupBox4.SuspendLayout();
			this.panel1.SuspendLayout();
			this.SuspendLayout();
			// 
			// lblCodeCount
			// 
			this.lblCodeCount.AutoSize = true;
			this.lblCodeCount.Font = new System.Drawing.Font("SimSun", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
			this.lblCodeCount.ForeColor = System.Drawing.Color.Red;
			this.lblCodeCount.Location = new System.Drawing.Point(6, 68);
			this.lblCodeCount.Name = "lblCodeCount";
			this.lblCodeCount.Size = new System.Drawing.Size(152, 16);
			this.lblCodeCount.TabIndex = 14;
			this.lblCodeCount.Text = "Number of barcodes";
			// 
			// btnClose
			// 
			this.btnClose.Font = new System.Drawing.Font("SimSun", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
			this.btnClose.Location = new System.Drawing.Point(84, 39);
			this.btnClose.Name = "btnClose";
			this.btnClose.Size = new System.Drawing.Size(74, 54);
			this.btnClose.TabIndex = 12;
			this.btnClose.Text = "Close DWS";
			this.btnClose.UseVisualStyleBackColor = true;
			this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
			// 
			// lblCode
			// 
			this.lblCode.AutoSize = true;
			this.lblCode.Font = new System.Drawing.Font("SimSun", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
			this.lblCode.ForeColor = System.Drawing.Color.Red;
			this.lblCode.Location = new System.Drawing.Point(6, 34);
			this.lblCode.Name = "lblCode";
			this.lblCode.Size = new System.Drawing.Size(128, 16);
			this.lblCode.TabIndex = 11;
			this.lblCode.Text = "Barcode content";
			this.lblCode.Click += new System.EventHandler(this.lblCode_Click);
			// 
			// gbBasic
			// 
			this.gbBasic.Controls.Add(this.button1);
			this.gbBasic.Controls.Add(this.btnStart);
			this.gbBasic.Controls.Add(this.btnClose);
			this.gbBasic.Font = new System.Drawing.Font("SimSun", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
			this.gbBasic.Location = new System.Drawing.Point(6, 126);
			this.gbBasic.Name = "gbBasic";
			this.gbBasic.Size = new System.Drawing.Size(242, 100);
			this.gbBasic.TabIndex = 16;
			this.gbBasic.TabStop = false;
			this.gbBasic.Text = "Basic Operation";
			// 
			// button1
			// 
			this.button1.Font = new System.Drawing.Font("SimSun", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
			this.button1.Location = new System.Drawing.Point(164, 39);
			this.button1.Name = "button1";
			this.button1.Size = new System.Drawing.Size(72, 54);
			this.button1.TabIndex = 13;
			this.button1.Text = "Soft Trigger";
			this.button1.UseVisualStyleBackColor = true;
			this.button1.Click += new System.EventHandler(this.button1_Click);
			// 
			// btnStart
			// 
			this.btnStart.Font = new System.Drawing.Font("SimSun", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
			this.btnStart.Location = new System.Drawing.Point(6, 39);
			this.btnStart.Name = "btnStart";
			this.btnStart.Size = new System.Drawing.Size(72, 54);
			this.btnStart.TabIndex = 10;
			this.btnStart.Text = "Start DWS";
			this.btnStart.UseVisualStyleBackColor = true;
			this.btnStart.Click += new System.EventHandler(this.btnStart_Click);
			// 
			// groupBox5
			// 
			this.groupBox5.Controls.Add(this.lblCode);
			this.groupBox5.Controls.Add(this.lblCodeCount);
			this.groupBox5.Font = new System.Drawing.Font("SimSun", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
			this.groupBox5.Location = new System.Drawing.Point(6, 7);
			this.groupBox5.Name = "groupBox5";
			this.groupBox5.Size = new System.Drawing.Size(657, 100);
			this.groupBox5.TabIndex = 17;
			this.groupBox5.TabStop = false;
			this.groupBox5.Text = "Current barcode";
			// 
			// listBoxLog
			// 
			this.listBoxLog.BackColor = System.Drawing.SystemColors.Control;
			this.listBoxLog.Dock = System.Windows.Forms.DockStyle.Fill;
			this.listBoxLog.ForeColor = System.Drawing.Color.Blue;
			this.listBoxLog.FormattingEnabled = true;
			this.listBoxLog.ItemHeight = 16;
			this.listBoxLog.Location = new System.Drawing.Point(3, 22);
			this.listBoxLog.Name = "listBoxLog";
			this.listBoxLog.Size = new System.Drawing.Size(647, 194);
			this.listBoxLog.TabIndex = 19;
			// 
			// groupBox4
			// 
			this.groupBox4.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.groupBox4.Controls.Add(this.listBoxLog);
			this.groupBox4.Font = new System.Drawing.Font("SimSun", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
			this.groupBox4.Location = new System.Drawing.Point(669, 7);
			this.groupBox4.Name = "groupBox4";
			this.groupBox4.Size = new System.Drawing.Size(653, 219);
			this.groupBox4.TabIndex = 20;
			this.groupBox4.TabStop = false;
			this.groupBox4.Text = "DWS Run Log";
			// 
			// Pan_Dis
			// 
			this.Pan_Dis.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.Pan_Dis.Location = new System.Drawing.Point(13, 14);
			this.Pan_Dis.Name = "Pan_Dis";
			this.Pan_Dis.Size = new System.Drawing.Size(1325, 547);
			this.Pan_Dis.TabIndex = 21;
			// 
			// panel1
			// 
			this.panel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.panel1.Controls.Add(this.groupBox4);
			this.panel1.Controls.Add(this.gbBasic);
			this.panel1.Controls.Add(this.groupBox5);
			this.panel1.Location = new System.Drawing.Point(8, 568);
			this.panel1.Name = "panel1";
			this.panel1.Size = new System.Drawing.Size(1330, 231);
			this.panel1.TabIndex = 21;
			// 
			// Form1DWS
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.SystemColors.Control;
			this.ClientSize = new System.Drawing.Size(1350, 811);
			this.Controls.Add(this.panel1);
			this.Controls.Add(this.Pan_Dis);
			this.Name = "Form1DWS";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Scan the code to demonstrate";
			this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_Closing);
			this.gbBasic.ResumeLayout(false);
			this.groupBox5.ResumeLayout(false);
			this.groupBox5.PerformLayout();
			this.groupBox4.ResumeLayout(false);
			this.panel1.ResumeLayout(false);
			this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Label lblCodeCount;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.Label lblCode;
        private System.Windows.Forms.ToolTip toolTip1;
        private System.Windows.Forms.GroupBox gbBasic;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.ListBox listBoxLog;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Panel Pan_Dis;
        private System.Windows.Forms.Panel panel1;
		private System.Windows.Forms.Button btnStart;
	}
}

