namespace DemoDWS
{
    partial class Form1DWS
    {
       ///<summary>
        ///Required designer variables.
        ///</summary>
        private System.ComponentModel.IContainer components = null;

///<summary>
        ///Clean up all resources in use.
        ///</summary>
        ///<param name="dispose"> true if managed resources should be released; otherwise, false. </param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Code generated by the form designer

        /// <summary>
        ///Designer supports required methods -do not modify
        ///Use the code editor to modify the contents of this method.
        /// </summary>
        private void InitializeComponent()
        {
			this.components = new System.ComponentModel.Container();
			this.btnClose = new System.Windows.Forms.Button();
			this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
			this.gbBasic = new System.Windows.Forms.GroupBox();
			this.btnStart = new System.Windows.Forms.Button();
			this.listBoxLog = new System.Windows.Forms.ListBox();
			this.groupBox4 = new System.Windows.Forms.GroupBox();
			this.Pan_Dis = new System.Windows.Forms.Panel();
			this.panel1 = new System.Windows.Forms.Panel();
			this.tlpCameras = new System.Windows.Forms.TableLayoutPanel();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.label2 = new System.Windows.Forms.Label();
			this.groupBox5 = new System.Windows.Forms.GroupBox();
			this.lblCode = new System.Windows.Forms.Label();
			this.gbBasic.SuspendLayout();
			this.groupBox4.SuspendLayout();
			this.panel1.SuspendLayout();
			this.tlpCameras.SuspendLayout();
			this.groupBox1.SuspendLayout();
			this.groupBox5.SuspendLayout();
			this.SuspendLayout();
			// 
			// btnClose
			// 
			this.btnClose.BackColor = System.Drawing.SystemColors.Window;
			this.btnClose.Font = new System.Drawing.Font("SimSun", 16F);
			this.btnClose.Location = new System.Drawing.Point(333, 40);
			this.btnClose.Name = "btnClose";
			this.btnClose.Size = new System.Drawing.Size(314, 54);
			this.btnClose.TabIndex = 12;
			this.btnClose.Text = "Close DWS";
			this.btnClose.UseVisualStyleBackColor = false;
			this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
			// 
			// gbBasic
			// 
			this.gbBasic.Controls.Add(this.btnStart);
			this.gbBasic.Controls.Add(this.btnClose);
			this.gbBasic.Font = new System.Drawing.Font("SimSun", 18F);
			this.gbBasic.Location = new System.Drawing.Point(6, 126);
			this.gbBasic.Name = "gbBasic";
			this.gbBasic.Size = new System.Drawing.Size(653, 100);
			this.gbBasic.TabIndex = 16;
			this.gbBasic.TabStop = false;
			this.gbBasic.Text = "Basic Operation";
			// 
			// btnStart
			// 
			this.btnStart.BackColor = System.Drawing.SystemColors.Window;
			this.btnStart.Font = new System.Drawing.Font("SimSun", 16F);
			this.btnStart.Location = new System.Drawing.Point(6, 40);
			this.btnStart.Name = "btnStart";
			this.btnStart.Size = new System.Drawing.Size(321, 54);
			this.btnStart.TabIndex = 10;
			this.btnStart.Text = "Start DWS";
			this.btnStart.UseVisualStyleBackColor = false;
			this.btnStart.Click += new System.EventHandler(this.btnStart_Click);
			// 
			// listBoxLog
			// 
			this.listBoxLog.BackColor = System.Drawing.SystemColors.Control;
			this.listBoxLog.Dock = System.Windows.Forms.DockStyle.Fill;
			this.listBoxLog.ForeColor = System.Drawing.Color.Blue;
			this.listBoxLog.FormattingEnabled = true;
			this.listBoxLog.ItemHeight = 16;
			this.listBoxLog.Location = new System.Drawing.Point(3, 22);
			this.listBoxLog.Name = "listBoxLog";
			this.listBoxLog.Size = new System.Drawing.Size(647, 75);
			this.listBoxLog.TabIndex = 19;
			// 
			// groupBox4
			// 
			this.groupBox4.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.groupBox4.Controls.Add(this.listBoxLog);
			this.groupBox4.Font = new System.Drawing.Font("SimSun", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
			this.groupBox4.Location = new System.Drawing.Point(669, 126);
			this.groupBox4.Name = "groupBox4";
			this.groupBox4.Size = new System.Drawing.Size(653, 100);
			this.groupBox4.TabIndex = 20;
			this.groupBox4.TabStop = false;
			this.groupBox4.Text = "DWS Run Log";
			// 
			// Pan_Dis
			// 
			this.Pan_Dis.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.Pan_Dis.Location = new System.Drawing.Point(13, 14);
			this.Pan_Dis.Name = "Pan_Dis";
			this.Pan_Dis.Size = new System.Drawing.Size(1325, 547);
			this.Pan_Dis.TabIndex = 21;
			// 
			// panel1
			// 
			this.panel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.panel1.Controls.Add(this.groupBox4);
			this.panel1.Controls.Add(this.gbBasic);
			this.panel1.Controls.Add(this.tlpCameras);
			this.panel1.Location = new System.Drawing.Point(8, 568);
			this.panel1.Name = "panel1";
			this.panel1.Size = new System.Drawing.Size(1330, 231);
			this.panel1.TabIndex = 21;
			// 
			// tlpCameras
			// 
			this.tlpCameras.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.tlpCameras.ColumnCount = 2;
			this.tlpCameras.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
			this.tlpCameras.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
			this.tlpCameras.Controls.Add(this.groupBox1, 1, 0);
			this.tlpCameras.Controls.Add(this.groupBox5, 0, 0);
			this.tlpCameras.Location = new System.Drawing.Point(6, 0);
			this.tlpCameras.Margin = new System.Windows.Forms.Padding(0);
			this.tlpCameras.Name = "tlpCameras";
			this.tlpCameras.RowCount = 1;
			this.tlpCameras.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
			this.tlpCameras.Size = new System.Drawing.Size(1318, 123);
			this.tlpCameras.TabIndex = 21;
			this.tlpCameras.Paint += new System.Windows.Forms.PaintEventHandler(this.tlpCameras_Paint);
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.Add(this.label2);
			this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.groupBox1.Font = new System.Drawing.Font("SimSun", 18F);
			this.groupBox1.Location = new System.Drawing.Point(665, 6);
			this.groupBox1.Margin = new System.Windows.Forms.Padding(6);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(647, 111);
			this.groupBox1.TabIndex = 18;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Camera 2";
			this.groupBox1.Enter += new System.EventHandler(this.groupBox1_Enter);
			// 
			// label2
			// 
			this.label2.AutoSize = true;
			this.label2.Font = new System.Drawing.Font("SimSun", 30F);
			this.label2.ForeColor = System.Drawing.Color.Black;
			this.label2.Location = new System.Drawing.Point(6, 40);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(0, 40);
			this.label2.TabIndex = 10;
			this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.label2.UseMnemonic = false;
			// 
			// groupBox5
			// 
			this.groupBox5.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
			this.groupBox5.Controls.Add(this.lblCode);
			this.groupBox5.Dock = System.Windows.Forms.DockStyle.Fill;
			this.groupBox5.Font = new System.Drawing.Font("SimSun", 18F);
			this.groupBox5.Location = new System.Drawing.Point(10, 10);
			this.groupBox5.Margin = new System.Windows.Forms.Padding(10);
			this.groupBox5.Name = "groupBox5";
			this.groupBox5.Size = new System.Drawing.Size(639, 103);
			this.groupBox5.TabIndex = 17;
			this.groupBox5.TabStop = false;
			this.groupBox5.Text = "Camera 1";
			this.groupBox5.Enter += new System.EventHandler(this.groupBox5_Enter);
			// 
			// lblCode
			// 
			this.lblCode.AutoSize = true;
			this.lblCode.Font = new System.Drawing.Font("SimSun", 30F);
			this.lblCode.ForeColor = System.Drawing.Color.Black;
			this.lblCode.Location = new System.Drawing.Point(6, 40);
			this.lblCode.Name = "lblCode";
			this.lblCode.Size = new System.Drawing.Size(0, 40);
			this.lblCode.TabIndex = 10;
			this.lblCode.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.lblCode.UseMnemonic = false;
			this.lblCode.Click += new System.EventHandler(this.lblCode_Click);
			// 
			// Form1DWS
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.SystemColors.Control;
			this.ClientSize = new System.Drawing.Size(1350, 811);
			this.Controls.Add(this.panel1);
			this.Controls.Add(this.Pan_Dis);
			this.Name = "Form1DWS";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Scan the code to demonstrate";
			this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_Closing);
			this.gbBasic.ResumeLayout(false);
			this.groupBox4.ResumeLayout(false);
			this.panel1.ResumeLayout(false);
			this.tlpCameras.ResumeLayout(false);
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			this.groupBox5.ResumeLayout(false);
			this.groupBox5.PerformLayout();
			this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.ToolTip toolTip1;
        private System.Windows.Forms.GroupBox gbBasic;
        private System.Windows.Forms.ListBox listBoxLog;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.Panel Pan_Dis;
        private System.Windows.Forms.Panel panel1;
		private System.Windows.Forms.Button btnStart;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.GroupBox groupBox5;
		private System.Windows.Forms.Label lblCode;
		private System.Windows.Forms.TableLayoutPanel tlpCameras;
	}
}

