namespace DemoDWS
{
    partial class ImageView
    {
        /// Required designer variables.
        private System.ComponentModel.IContainer components = null;

        /// Clean up all resources in use。
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by component designer

        /// Designer support required methods -Don't
        ///Use the code editor to modify the contents of this method.
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        }

        #endregion
    }
}
